version: 0.2
env:
  variables:
    ROLE_ARN: "arn:aws:iam::785773943475:role/codepipeline-deploy-role"
    SERVICE_NAME: "jcu-stg"
    CLUSTER_NAME: "jcu-stg-cluster"
    IMAGE_PATH: "785773943475.dkr.ecr.ap-southeast-2.amazonaws.com/jcu-stg-backend-ecr"
    ROLE_SESSION_NAME: "code-pipeline"


phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - echo Building the Docker image...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - source ci/ecr-login.sh ${DEPLOY_ROLE} ${AWS_PROFILE} ${IMAGE_PATH} 
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  build:
    commands:
      - echo Building the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
   post_build:
    commands:
      - echo deploy into ecs
      - source ci/assume_role.sh ${DEPLOY_ROLE} ${SERVICE_NAME} ${CLUSTER_NAME} ${IMAGE_NAME} ${env.BUILD_ID} ${AWS_PROFILE}
