version: 0.2

env:
  variables:
    DEPLOY_ROLE: "arn:aws:iam::754737238120:role/codepipeline-deploy-role"
    SERVICE_NAME: "codepipeline-testing-backend-service"
    CLUSTER_NAME: "codepipeline-testing-cluster"
    IMAGE_PATH: "754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr"

phases:
  pre_build:
    commands:
      - . ci/ecr-login.sh $ROLE $IMAGE_PATH
      - docker build -t codepipeline -f Dockerfile .
      - docker tag codepipeline:latest 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr:latest
  post_build:
    commands:
      - docker push 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr:latest

     
