version: 0.2

env:
  variables:
    DEPLOY_ROLE: "my_deploy_role"
    SERVICE_NAME: "codepipeline-testing-backend-service"
    CLUSTER_NAME: "codepipeline-testing-cluster"
    IMAGE_NAME: "754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr"
    AWS_PROFILE: "Devops-sandbox"

phases:
  pre_build:
    commands:
      - export AWS_PROFILE=Devops-sandbox
      - aws ecr get-login --no-include-email --region ap-southeast-2 | sh
  build:
    commands:
      - docker build -t codepipeline -f Dockerfile .
      - docker tag codepipeline:latest 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr:latest
  post_build:
    commands:
      - docker push 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline-testing-backend-ecr:latest
      - source ci/assume_role.sh ${DEPLOY_ROLE} ${SERVICE_NAME} ${CLUSTER_NAME} ${IMAGE_NAME} ${CODEBUILD_BUILD_ID} ${AWS_PROFILE}
     
