version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login --no-include-email --region ap-southeast-2 | sh
  build:
    commands:
      - docker build -t codepipeline:Latest .
      - docker tag codepipeline:latest 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline:latest
  post_build:
    commands:
      - docker push 754737238120.dkr.ecr.ap-southeast-2.amazonaws.com/codepipeline:latest
